# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ptViewer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1017, 807)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(20000, 20000))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_list_listView = QtWidgets.QListView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_list_listView.sizePolicy().hasHeightForWidth())
        self.file_list_listView.setSizePolicy(sizePolicy)
        self.file_list_listView.setObjectName("file_list_listView")
        self.horizontalLayout.addWidget(self.file_list_listView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_file_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.add_file_pushButton.setEnabled(True)
        self.add_file_pushButton.setObjectName("add_file_pushButton")
        self.verticalLayout.addWidget(self.add_file_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.up_file_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.up_file_pushButton.setObjectName("up_file_pushButton")
        self.verticalLayout.addWidget(self.up_file_pushButton)
        self.down_file_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.down_file_pushButton.setObjectName("down_file_pushButton")
        self.verticalLayout.addWidget(self.down_file_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.remove_file_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.remove_file_pushButton.setObjectName("remove_file_pushButton")
        self.verticalLayout.addWidget(self.remove_file_pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.expression_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.expression_lineEdit.setObjectName("expression_lineEdit")
        self.horizontalLayout_2.addWidget(self.expression_lineEdit)
        self.calculate_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.calculate_pushButton.setObjectName("calculate_pushButton")
        self.horizontalLayout_2.addWidget(self.calculate_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.excel_tabWidget = QtWidgets.QTabWidget(self.layoutWidget2)
        self.excel_tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.excel_tabWidget.setObjectName("excel_tabWidget")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.excel_page_tableView = QtWidgets.QTableView(self.tab)
        self.excel_page_tableView.setObjectName("excel_page_tableView")
        self.gridLayout.addWidget(self.excel_page_tableView, 0, 0, 1, 1)
        self.excel_tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.excel_tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.excel_tabWidget)
        self.save_file_pushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.save_file_pushButton.setObjectName("save_file_pushButton")
        self.verticalLayout_4.addWidget(self.save_file_pushButton)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1017, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.excel_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ptViewer"))
        self.label.setText(_translate("MainWindow", "Files to compare"))
        self.add_file_pushButton.setText(_translate("MainWindow", "Add"))
        self.up_file_pushButton.setText(_translate("MainWindow", "Up"))
        self.down_file_pushButton.setText(_translate("MainWindow", "Down"))
        self.remove_file_pushButton.setText(_translate("MainWindow", "Remove"))
        self.label_2.setText(_translate("MainWindow", "Layout Expression"))
        self.calculate_pushButton.setText(_translate("MainWindow", "Calculate"))
        self.excel_tabWidget.setTabText(self.excel_tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.excel_tabWidget.setTabText(self.excel_tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Page"))
        self.save_file_pushButton.setText(_translate("MainWindow", "Save as..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
